### ISSUE TITLE
Problems in the code

### ISSUE THREAD

**Issue by arduino183454** [NilsDengler/cluttered-pushing#2]
I cannot use 'import LazyThetaStarPython' in a virtual environment, but it can be used in a base environment. You know how to solve this problem. If you could tell me the solution, I would greatly appreciate it. Thank you. Also, could you provide these functions? I can't find them, thank you.
from arm_sim import ArmSim
from pybullet_cam import PyCam as Cam
from pybullet_environment_building import EnvBuild as build
from pybullet_collision_checker import ColCheck as collision
from debug_points import SphereMarker

**Comment by NilsDengler** [comment]
Hi, we are trying to fix all the problems mentioned in the next few days.

**Comment by arduino183454** [comment]
Thank you very much.

**Comment by NilsDengler** [comment]
We have updated and refactored some parts of the code, it should be usable now. Please refer to the new readme in the root folder. If there are any open questions, please feel free to ask me.
