### ISSUE TITLE
Missing Folder "evaluation" and question about the best_model

### ISSUE THREAD

**Issue by XUJIAZHANG2002** [NilsDengler/cluttered-pushing#4]
Hello, very impressed by your work and your clear, nice and clean code structure.

Is the model in Networks/RL/Logs/example_agent/model_test from the current version the best model we can get from the training?

Plus, in current version, push_gym/push_gym/evaluation is missing. 

Thanks for your amazing work and looking forward to your answer.

**Comment by NilsDengler** [comment]
As I wrote in the README, this is an example agent and not the agent used to reproduce the results of the paper.
Regarding the evaluation folder: I didn't have time to refactor the code in it, so all the files in the example folder are not usable for now, as they follow the old structure. For the sake of simplicity, I have removed them from the repository.

**Comment by XUJIAZHANG2002** [comment]
Thanks for your answer!
