### ISSUE TITLE
About push_gym/evaluation。

### ISSUE THREAD

**Issue by LeeChiAnn** [NilsDengler/cluttered-pushing#5]
Hello, excuse me！
Your code includes the following import statement: `from push_gym.evaluation.evaluation_function import Eval`, but in your file structure, there is no file or module named `evaluation`, which results in the inability to find the `Eval` class within the `evaluation_function` module.
Hello, I would like to ask what changes I need to make if I'm missing this file but I want to train the Agent.

**Comment by NilsDengler** [comment]
Dear @LeeChiAnn,
I fixed the problem and pushed the changes. Now you can just follow the instructions in the README. If there are any further issues, let me know.

**Comment by LeeChiAnn** [comment]
Dear @NilsDengler 
Thank you, and thank you for your paper's contribution to the field of reinforcement learning and robotics!
And I'm trying to understand the paper and the code.
