### ISSUE TITLE
TypeError: '<' not supported between instances of 'tuple' and 'int'

### ISSUE THREAD

**Issue by LeeChiAnn** [NilsDengler/cluttered-pushing#6]
**When I'm training the agent, it always reports an error around the 500,000th round.**
THE ERR :File ''cluttered-pushing/push_gym/push_gym/tasks/pushing.py", line 367, in step
    if self.current_obj_to_goal_theta_dist < 0: self.current_obj_to_goal_theta_dist = self.previous_obj_to_goal_theta_dist
TypeError: '<' not supported between instances of 'tuple' and 'int'

I added some code to determine the data type of `self.current_obj_to_goal_theta_dist`, and if it's a tuple, then assign `self.current_obj_to_goal_theta_dist[0]`.It still reports the same error：TypeError: '<' not supported between instances of 'tuple' and 'int'

**Even when I commented out this section of code:** 
 #calculate theta star path and subgoals
        self.current_obj_to_goal_theta_dist = self._calc_theta_distances()

        if isinstance(self.current_obj_to_goal_theta_dist, tuple):
            self.current_obj_to_goal_theta_dist = self.current_obj_to_goal_theta_dist[0]

        if self.current_obj_to_goal_theta_dist < 0: self.current_obj_to_goal_theta_dist = self.previous_obj_to_goal_theta_dist
        self.previous_obj_to_goal_theta_dist = self.current_obj_to_goal_theta_dist

**It still  reports the same error**：File ''cluttered-pushing/push_gym/push_gym/tasks/pushing.py", line 367, in step
    if self.current_obj_to_goal_theta_dist < 0: self.current_obj_to_goal_theta_dist = self.previous_obj_to_goal_theta_dist
TypeError: '<' not supported between instances of 'tuple' and 'int'

**Additionally, your code doesn't seem to be able to load  model, and I'm not sure why.**

**Comment by NilsDengler** [comment]
The question is why it switches between int and tuple at all.... I will check it if I can find some free time

**Comment by LeeChiAnn** [comment]
I have already resolved these two issues. Thank you. You can close this Issues.

**Comment by NilsDengler** [comment]
Hi @LeeChiAnn,
Can you elaborate on your solution or create a pull request so that others do not run into the same problem?

**Comment by LeeChiAnn** [comment]
Sure, I'll take some time to sort it out
